---
apiVersion: v1
kind: Service
metadata:
  name: easytravel-lb
  namespace: easytravel
  labels:
    app: easytravel-k8s
    type: frontend-pod
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: easytravel-lb
  selector:
    app: easytravel-k8s
    type: frontend-pod
  type: LoadBalancer
